###################################### User API ####################################

### userAPI

### Create a user
POST http://localhost:3000/user/register
Content-Type: application/json

{
    "username": "ASDAS",
    "password": "DSDSAS",
    "email": "ASDASW@gmail.abuabu"
}

### Login a user
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "ASDASW@gmail.abuabu",
    "password": "DSDSAS"
}

### Update a user
PUT http://localhost:3000/user
Content-Type: application/json

{
  "email": "newemail@example.com",
  "username": "newusername"
}


### Get user by Id
GET http://localhost:3000/user/675181b4c694d6098e2d1f24

###
DELETE http://localhost:3000/user/674f1b4375ac9ef1f436cf90



###################################### Post API ####################################

### create post

POST http://localhost:3000/post 
Content-Type: application/json

{
"user": "675181b4c694d6098e2d1f24", 
"username": "Sahar "
"message": "This is a new post"
}


###

### get all posts

GET http://localhost:3000/post

###

### get posts by id

GET http://localhost:3000/post/674f19d8bad94a891b79917b

###

### get posts by user

GET http://localhost:3000/post?user=674f185dde9f6f677a52401e

###

### update post

PUT http://localhost:3000/post/674f19d8bad94a891b79917b 
Content-Type: application/json

{
"message": "This age"
}

###

### delete post

DELETE http://localhost:3000/post/674f19d8bad94a891b79917b

###

###################################### Comment API ####################################


### create comment

POST http://localhost:3000/comment 
Content-Type: application/json

{
"user": "674f1b4375ac9ef1f436cf90", 
"message": "7439", 
"post": "674f1b5075ac9ef1f436cf92"
}

###

### get comment

GET http://localhost:3000/comment/674f1b6075ac9ef1f436cf95

###

### get comments by post

GET http://localhost:3000/comment?post=674f1b6075ac9ef1f436cf95

###

### update comment

PUT http://localhost:3000/comment/674f1b6075ac9ef1f436cf95 
Content-Type: application/json

{
"message": "This update"
}

###

### delete comment

DELETE http://localhost:3000/comment/674f1b6075ac9ef1f436cf95

###